name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GOPATH: ${{ github.workspace }}/go

    strategy:
      matrix:
        go-version: [1.20]

    steps:
      - uses: actions/checkout@v3
      - name: Use go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...